#!/usr/bin/env python
"""Generate the cross-run index: every run directory, labelled (issue #77).

Valid runs, probes and aborted launches used to be distinguishable only by
reading each directory's records. This writes `results/INDEX.md` and
`results/INDEX.csv` - one row per run directory - so comparability is
mechanical: every row carries its comparability FAMILY (from the city's
declared `docs/audit/run_families.json`, never re-derived here) and its
VALIDITY (status from `_meta.json`, whether `_run.json` exists, whether the
run relaxed), which is exactly the information whose absence lets someone
compare across families or fractions without noticing.

Classification is stated, not judged:

  * `aborted` / `failed` - the `_meta.json` status; no `_run.json`, never a
    result (`aborted_*` prefix is a label, the metadata is the truth);
  * `probe`  - completed but under 250 iterations, which DECISIONS.md 9.7/9.43
    MEASURED to be below any relaxation horizon - plumbing and timing evidence,
    never a result;
  * `arm`    - a completed run at or above that horizon; whether it RELAXED is
    its own column, read from `_summary.json`.

Per-mode fit is copied from `_fit.json` where one exists - every mode
individually, never an aggregate row (standing directive). The index is
REGENERATED by this script and never hand-edited; it lives in `results/`
(gitignored) beside what it indexes.

    python src/analyse/build_run_index.py
"""
import argparse
import csv
import io
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(_HERE))
sys.path.insert(0, os.path.join(ROOT, 'src'))
import city  # noqa: E402
import registry as _registry  # noqa: E402

RESULTS = os.path.join(ROOT, 'results')
# Below this iteration count a completed run is a probe. Not a constant of this
# script's own: it is the declared sweep FLOOR of RUN.controler.last_iteration,
# whose basis reads "the largest value MEASURED to be insufficient"
# (DECISIONS.md 9.7, 9.43) - exactly the probe/arm boundary.
PROBE_ITERATIONS_CEILING = _registry.load().sweep(
    'RUN.controler.last_iteration')['interval'][0]


def load_families():
    path = city.path('docs', 'audit', 'run_families.json')
    with open(path, encoding='utf-8') as f:
        doc = json.load(f)
    fams = sorted(doc['families'].items(), key=lambda kv: kv[1]['from_launch'])
    return fams, doc.get('overrides', {})


def launch_stamp(name):
    """The yyyymmddThhmmss launch stamp out of a runner-scheme directory name."""
    stem = name[len('aborted_'):] if name.startswith('aborted_') else name
    stamp = stem.split('_', 1)[0]
    return stamp if len(stamp) == 15 and stamp[8] == 'T' else None


def family_of(name, fams, overrides):
    if name in overrides:
        return overrides[name].get('family'), overrides[name].get('note', '')
    stamp = launch_stamp(name)
    if stamp is None:
        return None, 'directory name is not in the runner scheme'
    assigned = None
    for fam_id, fam in fams:
        if fam['from_launch'] <= stamp:
            assigned = fam_id
    return assigned, ''


def _load(run_dir, filename):
    try:
        with open(os.path.join(run_dir, filename), encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def scan_run(name, fams, overrides):
    run_dir = os.path.join(RESULTS, name)
    meta = _load(run_dir, '_meta.json') or {}
    record = _load(run_dir, '_run.json')
    summary = _load(run_dir, '_summary.json') or {}
    fit = _load(run_dir, '_fit.json')

    family, fam_note = family_of(name, fams, overrides)
    status = meta.get('status') or ('completed' if record else 'unknown')
    has_record = record is not None
    relaxed = (summary.get('relaxation') or {}).get('relaxed')

    if not has_record:
        run_class = status if status in ('failed', 'aborted') else 'no-record'
    elif (record.get('iterations') or 0) < PROBE_ITERATIONS_CEILING:
        run_class = 'probe'
    else:
        run_class = 'arm'

    src = record or meta
    warm = src.get('warm_started_from') or meta.get('warm_started_from')
    row = {
        'name': name,
        'class': run_class,
        'status': status,
        'run_record': 'yes' if has_record else 'no',
        'relaxed': {True: 'yes', False: 'no'}.get(relaxed, ''),
        'family': family or 'unattributed',
        'family_note': fam_note,
        'scenario': src.get('scenario'),
        'day': src.get('day'),
        'fraction': src.get('fraction'),
        'iterations': src.get('iterations'),
        'seed': src.get('seed'),
        'threads': src.get('threads'),
        'median_iteration_s': (record or {}).get('median_iteration_s'),
        'warm_started_from': ('%s@it%s' % (warm['run'], warm['iteration'])
                              if warm else ''),
        'controler_sha256': (src.get('controler_sha256') or '')[:12],
    }
    modes = []
    if fit:
        for e in (fit.get('mode_share') or {}).get('errors', []):
            modes.append({'mode': e.get('matsim_mode'),
                          'hts_category': e.get('hts_category'),
                          'modelled': e.get('modelled'),
                          'observed': e.get('observed'),
                          'pct_error': e.get('pct_error')})
        row['fit_mae_pp'] = (fit.get('mode_share') or {}).get('mean_abs_pp')
    else:
        row['fit_mae_pp'] = None
    return row, modes


CSV_COLUMNS = ['name', 'class', 'status', 'run_record', 'relaxed', 'family',
               'scenario', 'day', 'fraction', 'iterations', 'seed', 'threads',
               'median_iteration_s', 'fit_mae_pp', 'warm_started_from',
               'controler_sha256', 'family_note']


def build():
    fams, overrides = load_families()
    names = sorted(d for d in os.listdir(RESULTS)
                   if os.path.isdir(os.path.join(RESULTS, d))
                   and not d.startswith('_'))
    rows, per_mode = [], {}
    for name in names:
        row, modes = scan_run(name, fams, overrides)
        rows.append(row)
        if modes:
            per_mode[name] = modes

    csv_path = os.path.join(RESULTS, 'INDEX.csv')
    with io.open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        w.writeheader()
        for row in rows:
            w.writerow({k: ('' if row.get(k) is None else row.get(k))
                        for k in CSV_COLUMNS})

    md_path = os.path.join(RESULTS, 'INDEX.md')
    with io.open(md_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('# Run index - generated by src/analyse/build_run_index.py; '
                'NEVER hand-edit\n\n')
        f.write('One row per run directory. **Comparisons are legitimate only '
                'inside one family at one fraction** (DECISIONS.md 3.5 and the '
                'family boundaries in docs/audit/run_families.json). A run '
                'without `_run.json` is not a result; a `probe` (under %d '
                'iterations, DECISIONS.md 9.7/9.43) is plumbing/timing '
                'evidence, never a result.\n\n' % PROBE_ITERATIONS_CEILING)
        f.write('| run | class | status | record | relaxed | family | S | day '
                '| frac | iters | seed | thr | med s/it | fit MAE pp |\n')
        f.write('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n')
        for r in rows:
            f.write('| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s '
                    '| %s | %s | %s |\n'
                    % tuple('' if v is None else v for v in (
                        r['name'], r['class'], r['status'], r['run_record'],
                        r['relaxed'], r['family'], r['scenario'], r['day'],
                        r['fraction'], r['iterations'], r['seed'],
                        r['threads'], r['median_iteration_s'],
                        r['fit_mae_pp'])))
        if per_mode:
            f.write('\n## Per-mode fit, where a `_fit.json` exists\n\n'
                    'Every mode individually - no aggregate rows. These are '
                    'the runs\' own fit records copied through, pre-calibration '
                    'report cards, not findings.\n')
            for name, modes in sorted(per_mode.items()):
                f.write('\n### %s\n\n' % name)
                f.write('| mode | HTS category | modelled | observed | %% error |\n')
                f.write('|---|---|---|---|---|\n')
                for m in modes:
                    f.write('| %s | %s | %s | %s | %s |\n'
                            % (m['mode'], m['hts_category'], m['modelled'],
                               m['observed'], m['pct_error']))
        notes = [r for r in rows if r['family_note']]
        if notes:
            f.write('\n## Attribution notes\n\n')
            for r in notes:
                f.write('- **%s**: %s\n' % (r['name'], r['family_note']))
    return csv_path, md_path, len(rows)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.parse_args()
    csv_path, md_path, n = build()
    print('indexed %d run directories\n  %s\n  %s' % (n, csv_path, md_path))
    return 0


if __name__ == '__main__':
    sys.exit(main())
